
[build-system]
requires = ["setuptools"]

[project]
name = "algs"
version = "0.0.1"

description = "Data Structures and Algorithms"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["."]
